### ISSUE TITLE
Second smallest suggestion

### ISSUE THREAD

**Issue by Jsdemonsim** [gareins/second-smallest#1]
I didn't know the best way to contact you, so I opened this issue.  You current one loop solution looks like this:

    if (*iter < first) {
        second = first;
        first = *iter;
    } else if (*iter < second) {
        second = *iter;
    }

This way uses two comparisons per item, unless the new item is the smallest item.  I modified this code to look like this instead, to reduce the number of comparisons:

    if (*iter < second) {
        if (*iter < first) {
            second = first;
            first = *iter;
        } else {
            second = *iter;
        }
    }

This way uses one comparison per item, unless the new item is one of the two smallest.  In the general case where the input is in random order, this version will be far more likely to use 1 comparison than 2.  From my own testing, this resulted in a faster time.  Perhaps you could try this version versus all your other methods as well.

**Comment by gareins** [comment]
Of course, it is indeed faster. I somehow did not see that, I'll put it in.
